import Head from 'next/head'
import { createContext, useState } from 'react'
import HomePage from './HomePage/HomePage'
import style from "@/styles/HomePage.module.css"
import { THEME, ThemeContext } from '@/types/Theme'


export default function Home()
{

  const [theme, setTheme] = useState(THEME.LIGHT)

  const handleThemeToggle = () => {
    if (theme === THEME.LIGHT) setTheme(THEME.DARK)
    else setTheme(THEME.LIGHT)
  }

  return (
    <>
      <ThemeContext.Provider value={theme}>
        <div className={`${style.themebutta}`} onClick={handleThemeToggle}>
          {(theme === THEME.LIGHT) ? `☀️` : `🌕`}
        </div>
        <Head>
          <title>Old Egg</title>
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" />
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={style.global} style={{backgroundColor: theme.background, color: theme.textColor}} >
          <HomePage />
        </main>
      </ThemeContext.Provider>
    </>

  )
}
